In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("4. Covid_19_data.csv")
print(data)

          Date     State          Region  Confirmed  Deaths  Recovered
0    4/29/2020       NaN     Afghanistan       1939      60        252
1    4/29/2020       NaN         Albania        766      30        455
2    4/29/2020       NaN         Algeria       3848     444       1702
3    4/29/2020       NaN         Andorra        743      42        423
4    4/29/2020       NaN          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[321 rows x 6 columns]

In [4]:
data.head()

        Date State       Region  Confirmed  Deaths  Recovered
0  4/29/2020   NaN  Afghanistan       1939      60        252
1  4/29/2020   NaN      Albania        766      30        455
2  4/29/2020   NaN      Algeria       3848     444       1702
3  4/29/2020   NaN      Andorra        743      42        423
4  4/29/2020   NaN       Angola         27       2          7

In [5]:
data.columns

Index(['Date', 'State', 'Region', 'Confirmed', 'Deaths', 'Recovered'], dtype='object')

In [6]:
data.info

<bound method DataFrame.info of           Date     State          Region  Confirmed  Deaths  Recovered
0    4/29/2020       NaN     Afghanistan       1939      60        252
1    4/29/2020       NaN         Albania        766      30        455
2    4/29/2020       NaN         Algeria       3848     444       1702
3    4/29/2020       NaN         Andorra        743      42        423
4    4/29/2020       NaN          Angola         27       2          7
..         ...       ...             ...        ...     ...        ...
316  4/29/2020   Wyoming              US        545       7          0
317  4/29/2020  Xinjiang  Mainland China         76       3         73
318  4/29/2020     Yukon          Canada         11       0          0
319  4/29/2020    Yunnan  Mainland China        185       2        181
320  4/29/2020  Zhejiang  Mainland China       1268       1       1263

[321 rows x 6 columns]>

In [7]:
data.describe()

           Confirmed        Deaths      Recovered
count     321.000000    321.000000     321.000000
mean     9949.800623    709.152648    3030.277259
std     31923.853086   3236.162817   14364.870365
min         0.000000      0.000000       0.000000
25%       104.000000      2.000000       2.000000
50%       653.000000     12.000000      73.000000
75%      4655.000000    144.000000     587.000000
max    299691.000000  27682.000000  132929.000000

In [8]:
data.isnull().sum()

Date           0
State        181
Region         0
Confirmed      0
Deaths         0
Recovered      0
dtype: int64

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
data.groupby("Region")["Confirmed"].sum()

Region
Afghanistan           1939
Albania                766
Algeria               3848
Andorra                743
Angola                  27
                      ...
West Bank and Gaza     344
Western Sahara           6
Yemen                    6
Zambia                  97
Zimbabwe                32
Name: Confirmed, Length: 187, dtype: int64

In [11]:
data.groupby("Region")["Deaths"].sum()

Region
Afghanistan            60
Albania                30
Algeria               444
Andorra                42
Angola                  2
                     ...
West Bank and Gaza      2
Western Sahara          0
Yemen                   0
Zambia                  3
Zimbabwe                4
Name: Deaths, Length: 187, dtype: int64

In [12]:
data1=data.groupby("Region")["Recovered"].sum()
print(data1)

Region
Afghanistan            252
Albania                455
Algeria               1702
Andorra                423
Angola                   7
                      ...
West Bank and Gaza      71
Western Sahara           5
Yemen                    1
Zambia                  54
Zimbabwe                 5
Name: Recovered, Length: 187, dtype: int64

In [13]:
data.groupby("Region")["Confirmed"].sum().sort_values(ascending=False).head(5)

Region
US        1039909
Spain      236899
Italy      203591
France     166543
UK         166441
Name: Confirmed, dtype: int64

In [14]:
data.groupby("Region")["Confirmed"].sum().sort_values(ascending=True).head(5)

Region
Yemen                    6
Western Sahara           6
Bhutan                   7
Papua New Guinea         8
Sao Tome and Principe    8
Name: Confirmed, dtype: int64

In [15]:
data.groupby("Region")["Deaths"].sum().sort_values(ascending=False).head(10)

Region
US             60967
Italy          27682
UK             26166
Spain          24275
France         24121
Belgium         7501
Germany         6467
Iran            5957
Brazil          5513
Netherlands     4727
Name: Deaths, dtype: int64

In [16]:
data[data.Region=="India"]

         Date State Region  Confirmed  Deaths  Recovered
74  4/29/2020   NaN  India      33062    1079       8437

In [17]:
data[data.Region=="Brazil"]

         Date State  Region  Confirmed  Deaths  Recovered
22  4/29/2020   NaN  Brazil      79685    5513      34132

In [18]:
data.sort_values(by=['Confirmed'],ascending=False)

,Date,State,Region,Confirmed,Deaths,Recovered
265,4/29/2020,New York,US,299691,23477,0
153,4/29/2020,NaN,Spain,236899,24275,132929
80,4/29/2020,NaN,Italy,203591,27682,71252
168,4/29/2020,NaN,UK,165221,26097,0
57,4/29/2020,NaN,France,165093,24087,48228
...,...,...,...,...,...,...
305,4/29/2020,Tibet,Mainland China,1,0,1
289,4/29/2020,Saint Pierre and Miquelon,France,1,0,0
285,4/29/2020,Recovered,US,0,0,120720
284,4/29/2020,Recovered,Canada,0,0,20327
203,4/29/2020,Diamond Princess cruise ship,Canada,0,1,0

In [19]:
data.sort_values(by=['Recovered'],ascending=False)

          Date           State   Region  Confirmed  Deaths  Recovered
153  4/29/2020             NaN    Spain     236899   24275     132929
285  4/29/2020       Recovered       US          0       0     120720
61   4/29/2020             NaN  Germany     161539    6467     120400
76   4/29/2020             NaN     Iran      93657    5957      73791
80   4/29/2020             NaN    Italy     203591   27682      71252
..         ...             ...      ...        ...     ...        ...
248  4/29/2020        Maryland       US      20849    1078          0
246  4/29/2020        Manitoba   Canada        275       6          0
243  4/29/2020       Louisiana       US      27660    1845          0
241  4/29/2020        Kentucky       US       4537     234          0
215  4/29/2020  Grand Princess   Canada         13       0          0

[321 rows x 6 columns]